### PR TITLE
Deployable to heroku

### PR DESCRIPTION
**Pull request by PandazNetwork**
1. app.json added
2. heroku deploy button added to readme file

### CODE REVIEW

**Comment by bipinkrish** [comment]
Have you deployed it?

**Comment by PandazNetwork** [comment]
Yes I am using your repo on heroku from last 4 months

**Comment by bipinkrish** [comment]
Make this changes:
	1. Remove Deploying on Replit block
	2. `keywords` in `app.json` are not suitable for this project, change it accordingly
	
Optional Changes:
	1. You can add all other ENVs that is supported by the repo in `app.json`

**Comment by PandazNetwork** [comment]
Ok making changes 👍

**Comment by PandazNetwork** [comment]
I will do optional changes till evening in next commit

**Comment by bipinkrish** [comment]
remove `Installation` also

**Comment by PandazNetwork** [comment]
Done

**Comment by PandazNetwork** [comment]
bro updated all things, 
Removed Deploying on Replit block
updated keywords in app.json
added all other ENVs that is supported by the repo in app.json

**Pull request merged**
