### PR TITLE
Shortner Full Page API Support

### PR DESCRIPTION
**Pull request by AnshumanPM**

### CODE REVIEW

**Comment by bipinkrish** [comment]
Is it from IGG?

**Comment by AnshumanPM** [comment]
IGG 🤔?

**Comment by bipinkrish** [comment]
Why did you added condition in igggames?

**Comment by AnshumanPM** [comment]
No it's not related to igggames it's related to all shortener's full page feature

Ex Link - https://atglinks.com/full?api=c21a3e6198013bb8d64a469008b336d6b6c9e78a&url=aHR0cHM6Ly9uZXJkLmdkZmxpeC5pbmsvZmlsZS9yc0VxVkRCMTQy&type=2

**Comment by bipinkrish** [comment]
You are calling the same function two times, save it in a variable and return that

**Pull request merged**
